server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/imagination
    username: webserver
    password: webserver
    hikari:
      auto-commit: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    show-sql: true

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB

  data.rest:
    base-path: /api
    detection-strategy: annotated
